// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using com.b_velop.Slipways.GraphQL.Data;

namespace com.b_velop.Slipways.GraphQL.Migrations
{
    [DbContext(typeof(SlipwaysContext))]
    partial class SlipwaysContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("com.b_velop.Slipways.GraphQL.Data.Models.Slipway", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Costs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postalcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<Guid>("WaterFk")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WaterFk");

                    b.ToTable("Slipways");
                });

            modelBuilder.Entity("com.b_velop.Slipways.GraphQL.Data.Models.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Agency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Km")
                        .HasColumnType("float");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Longname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shortname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("WaterFk")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WaterFk");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("com.b_velop.Slipways.GraphQL.Data.Models.Water", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Longname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shortname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Waters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ffa035bd-4c18-4a12-9bc7-5e66fc29e149"),
                            Longname = "ALLER",
                            Shortname = "ALLER"
                        },
                        new
                        {
                            Id = new Guid("be09d030-9c00-4a2d-83cf-222a469b317a"),
                            Longname = "BERLIN-SPANDAUER-SCHIFFFAHRTSKANAL",
                            Shortname = "BSK"
                        },
                        new
                        {
                            Id = new Guid("3a2495f2-4581-43c1-8061-426525b1815a"),
                            Longname = "BODENSEE",
                            Shortname = "BODENSEE"
                        },
                        new
                        {
                            Id = new Guid("fadeb941-fe23-40f4-b1cd-5c949dc8372f"),
                            Longname = "BÜTZFLETHER SÜDERELBE",
                            Shortname = "Bützflether Süderelbe"
                        },
                        new
                        {
                            Id = new Guid("ba4ac402-5733-4608-acd0-bc1edfd1a157"),
                            Longname = "DAHME-WASSERSTRASSE",
                            Shortname = "DAW"
                        },
                        new
                        {
                            Id = new Guid("28cdf699-e727-447b-b3ee-9d10f8b2a5b2"),
                            Longname = "DATTELN-HAMM-KANAL",
                            Shortname = "DHK"
                        },
                        new
                        {
                            Id = new Guid("75a1d3e7-c6e7-4b50-85e9-c74ca31b0b5f"),
                            Longname = "DIEMEL",
                            Shortname = "DIEMEL"
                        },
                        new
                        {
                            Id = new Guid("d19708ca-ac42-4ad4-8d62-e85722f946f6"),
                            Longname = "DONAU",
                            Shortname = "DONAU"
                        },
                        new
                        {
                            Id = new Guid("96423534-6b1a-4af8-93d7-6f99af296ecd"),
                            Longname = "DORTMUND-EMS-KANAL",
                            Shortname = "DEK"
                        },
                        new
                        {
                            Id = new Guid("c23322c5-ad2a-4050-9e64-e377341617a9"),
                            Longname = "DYHRSSENMOOR",
                            Shortname = "DYHRSSENMOOR"
                        },
                        new
                        {
                            Id = new Guid("afc35e3e-2400-4e4d-82d1-c11e3b3274d2"),
                            Longname = "EDER",
                            Shortname = "EDER"
                        },
                        new
                        {
                            Id = new Guid("e2b58ea1-969f-4f72-a2a6-429c7fdd8f37"),
                            Longname = "EIDER",
                            Shortname = "EIDER"
                        },
                        new
                        {
                            Id = new Guid("de3724fd-80a8-46f9-8b5b-db378a84048c"),
                            Longname = "ELBE",
                            Shortname = "ELBE"
                        },
                        new
                        {
                            Id = new Guid("b35aa52d-9188-4489-8189-73f4e6b9841e"),
                            Longname = "ELBE-HAVEL-KANAL",
                            Shortname = "EHK"
                        },
                        new
                        {
                            Id = new Guid("f5d543c2-b584-40e4-afa0-19435627e3ff"),
                            Longname = "ELBESEITENKANAL",
                            Shortname = "ESK"
                        },
                        new
                        {
                            Id = new Guid("7eef13f6-e9be-4ca4-8f03-30c4aa75e493"),
                            Longname = "ELK",
                            Shortname = "ELBE-LÜBECK-KANAL"
                        },
                        new
                        {
                            Id = new Guid("ed0e2086-7425-4d2d-b372-d9b219d5638b"),
                            Longname = "EMS",
                            Shortname = "EMS"
                        },
                        new
                        {
                            Id = new Guid("1836bb37-423e-444b-bf2e-df21fed87fb1"),
                            Longname = "ESTE",
                            Shortname = "ESTE"
                        },
                        new
                        {
                            Id = new Guid("637cbed8-f8a3-41a4-a649-cfed2613c6cb"),
                            Longname = "FINOWKANAL",
                            Shortname = "FiK"
                        },
                        new
                        {
                            Id = new Guid("fea68b1b-7080-428d-9180-3a2fabf95d71"),
                            Longname = "FREIBURGER HAFENPRIEL",
                            Shortname = "Freiburger Hafenpriel"
                        },
                        new
                        {
                            Id = new Guid("966076cc-19e7-4922-921d-aad15d5164b1"),
                            Longname = "FULDA",
                            Shortname = "FULDA"
                        },
                        new
                        {
                            Id = new Guid("e9b9cd69-3073-4002-a0f6-37c2153c53ec"),
                            Longname = "HAMME",
                            Shortname = "HAMME"
                        },
                        new
                        {
                            Id = new Guid("fb9b6f64-a7a6-4744-a12f-5bdf31e6f0af"),
                            Longname = "HAVEL-ODER-WASSERSTRASSE",
                            Shortname = "HOW"
                        },
                        new
                        {
                            Id = new Guid("d54f6551-d1f2-4856-a873-86a6e17eebb4"),
                            Longname = "HAVELKANAL",
                            Shortname = "HvK"
                        },
                        new
                        {
                            Id = new Guid("0bc5bdb3-7e62-4c28-b4d3-fd4d3e7580c8"),
                            Longname = "HUNTE",
                            Shortname = "HUNTE"
                        },
                        new
                        {
                            Id = new Guid("90398d4a-b576-431d-ad9a-3a632a333daa"),
                            Longname = "ILM",
                            Shortname = "ILM"
                        },
                        new
                        {
                            Id = new Guid("0f4ceb73-146d-474e-8232-3cabbccc27e7"),
                            Longname = "ILMENAU",
                            Shortname = "ILMENAU"
                        },
                        new
                        {
                            Id = new Guid("aa74ebd7-e4b1-4ea4-83e2-989d94b90d6a"),
                            Longname = "ITTER ZUR DIEMEL",
                            Shortname = "ITTER_DIEMEL"
                        },
                        new
                        {
                            Id = new Guid("2063f11b-3b00-41a6-baea-2de71e34e5da"),
                            Longname = "ITTER ZUR EDER",
                            Shortname = "ITTER EDER"
                        },
                        new
                        {
                            Id = new Guid("a237b616-e51b-4c6c-8fe2-ef485b0a3879"),
                            Longname = "JADE",
                            Shortname = "JADE"
                        },
                        new
                        {
                            Id = new Guid("b22c66a1-fedc-4822-83c7-5918ef35d35d"),
                            Longname = "JIZERA",
                            Shortname = "Jizera"
                        },
                        new
                        {
                            Id = new Guid("dcc5eb65-dee4-4bd5-a61b-80d3dfa54c41"),
                            Longname = "KLEINES HAFF",
                            Shortname = "KLEINES HAFF"
                        },
                        new
                        {
                            Id = new Guid("2e1a8e9d-983f-445b-8f31-270510396d90"),
                            Longname = "KRÜCKAU",
                            Shortname = "KRÜCKAU"
                        },
                        new
                        {
                            Id = new Guid("283901d1-24a4-4e8e-94f6-3fa3dfb4720a"),
                            Longname = "KÜSTENKANAL",
                            Shortname = "KÜSTENKANAL"
                        },
                        new
                        {
                            Id = new Guid("fd74ae1f-78c3-4efa-8449-6ecc1fb482ab"),
                            Longname = "LAHN",
                            Shortname = "LAHN"
                        },
                        new
                        {
                            Id = new Guid("d7818e64-186b-435f-a871-cdb9f75d4459"),
                            Longname = "LANDWEHRKANAL",
                            Shortname = "LWK"
                        },
                        new
                        {
                            Id = new Guid("48052b97-14e6-43a6-b096-7e7b4e95ee66"),
                            Longname = "LEDA",
                            Shortname = "LEDA"
                        },
                        new
                        {
                            Id = new Guid("821630fc-d361-458f-b69c-2115a1c10b24"),
                            Longname = "LEINE",
                            Shortname = "LEINE"
                        },
                        new
                        {
                            Id = new Guid("171de910-9dbe-4b30-a4d7-a79e231fc411"),
                            Longname = "LESUM",
                            Shortname = "LESUM"
                        },
                        new
                        {
                            Id = new Guid("40c51e0c-d21c-492a-bbab-e9af3acc0187"),
                            Longname = "LYCHENER GEWÄSSER",
                            Shortname = "LyG"
                        },
                        new
                        {
                            Id = new Guid("5980613c-07da-44b7-bda4-5de17f9c20e5"),
                            Longname = "LÜHE",
                            Shortname = "LÜHE"
                        },
                        new
                        {
                            Id = new Guid("2f14ff08-2c57-4da3-9c69-2978efd4ac6e"),
                            Longname = "MAIN",
                            Shortname = "MAIN"
                        },
                        new
                        {
                            Id = new Guid("5f6f4fcf-e1cb-472e-8fd3-f331875e5153"),
                            Longname = "MAIN-DONAU-KANAL",
                            Shortname = "MDK"
                        },
                        new
                        {
                            Id = new Guid("a8aca94c-fe23-43e0-93a7-39a6614b5d87"),
                            Longname = "MALZER KANAL",
                            Shortname = "MZK"
                        },
                        new
                        {
                            Id = new Guid("09a03b1f-9ece-4086-94d8-462f98985851"),
                            Longname = "MITTELLANDKANAL",
                            Shortname = "MLK"
                        },
                        new
                        {
                            Id = new Guid("aae1f1d4-f79f-4c3a-83d5-debffd711981"),
                            Longname = "MOSEL",
                            Shortname = "MOSEL"
                        },
                        new
                        {
                            Id = new Guid("de958aa1-aa8c-482b-8d76-11c9b8c68c47"),
                            Longname = "MÜGGELSPREE",
                            Shortname = "MGS"
                        },
                        new
                        {
                            Id = new Guid("e54e5839-5fc8-4494-9360-8989442a2242"),
                            Longname = "MÜRITZ-ELDE-WASSERSTRASSE",
                            Shortname = "MEW"
                        },
                        new
                        {
                            Id = new Guid("8c8c8518-d59b-4512-b75c-36a67f95c260"),
                            Longname = "MÜRITZ-HAVEL-WASSERSTRASSE",
                            Shortname = "MHW"
                        },
                        new
                        {
                            Id = new Guid("afc18147-790a-4af0-bffa-a54156c6ba7c"),
                            Longname = "NECKAR",
                            Shortname = "NECKAR"
                        },
                        new
                        {
                            Id = new Guid("9e207d14-f5a8-43b0-b7b0-1d4c484e5444"),
                            Longname = "NEUHAUSER SPEISEKANAL",
                            Shortname = "NSK"
                        },
                        new
                        {
                            Id = new Guid("5963233a-8e39-459e-931c-e27c057a49b6"),
                            Longname = "NIEGRIPPER VERBINDUNGSKANAL",
                            Shortname = "NVK"
                        },
                        new
                        {
                            Id = new Guid("e5c5d288-6a87-42ec-81c1-d58f1a6fcf1b"),
                            Longname = "NORD-OSTSEE-KANAL",
                            Shortname = "Nord-Ostsee-Kanal"
                        },
                        new
                        {
                            Id = new Guid("1a191392-64f3-408e-87f0-b91e10545b57"),
                            Longname = "NORDSEE",
                            Shortname = "NORDSEE"
                        },
                        new
                        {
                            Id = new Guid("89658af6-0df5-42bf-b550-5923fadc6f33"),
                            Longname = "OBERE HAVEL-WASSERSTRASSE",
                            Shortname = "OHW"
                        },
                        new
                        {
                            Id = new Guid("6ce9c61c-ab43-4084-bd62-9ad5e2ab6cf9"),
                            Longname = "ODER",
                            Shortname = "ODER"
                        },
                        new
                        {
                            Id = new Guid("e9f60b79-5fde-4026-b6a2-fb27112135e7"),
                            Longname = "OHRE",
                            Shortname = "EGER"
                        },
                        new
                        {
                            Id = new Guid("aabc9e69-6dae-4f35-9250-8427eaedf15c"),
                            Longname = "ORANIENBURGER KANAL",
                            Shortname = "OrK"
                        },
                        new
                        {
                            Id = new Guid("3883de67-ab59-458a-9de1-1e1026e27bf0"),
                            Longname = "ORKE",
                            Shortname = "ORKE"
                        },
                        new
                        {
                            Id = new Guid("529fc755-8b44-44be-a56f-0d751b82e76a"),
                            Longname = "ORLICE",
                            Shortname = "Orlice"
                        },
                        new
                        {
                            Id = new Guid("bac6f0b5-34e1-4425-a1d6-05624aa72fdd"),
                            Longname = "OSTE",
                            Shortname = "OSTE"
                        },
                        new
                        {
                            Id = new Guid("0c5ecb8f-5c72-4e55-82c5-cff6a068f5a4"),
                            Longname = "OSTSEE",
                            Shortname = "OSTSEE"
                        },
                        new
                        {
                            Id = new Guid("1a23b4ab-db97-4f74-bce9-151db100b0b0"),
                            Longname = "PAREYER VERBINDUNGSKANAL",
                            Shortname = "PVK"
                        },
                        new
                        {
                            Id = new Guid("fb88f5b1-2248-45ca-bd47-1a2213b82fd3"),
                            Longname = "PEENE",
                            Shortname = "PEENE"
                        },
                        new
                        {
                            Id = new Guid("8eb3c12d-029c-48f7-8995-d04f2d76f815"),
                            Longname = "PINNAU",
                            Shortname = "PINNAU"
                        },
                        new
                        {
                            Id = new Guid("acb1b45d-4161-4c4a-a518-c508ed5a03b5"),
                            Longname = "POTSDAMER HAVEL",
                            Shortname = "PHv"
                        },
                        new
                        {
                            Id = new Guid("a88ea916-5e6c-4d83-83a9-1d4fdfef25ec"),
                            Longname = "RHEIN",
                            Shortname = "RHEIN"
                        },
                        new
                        {
                            Id = new Guid("30081c46-bbe9-4ac7-894c-4852476d66e5"),
                            Longname = "RHEIN-HERNE-KANAL",
                            Shortname = "RHK"
                        },
                        new
                        {
                            Id = new Guid("9752610e-8cf8-4ef9-b820-666df89a720a"),
                            Longname = "RHEINSBERGER GEWÄSSER",
                            Shortname = "RBG"
                        },
                        new
                        {
                            Id = new Guid("c486d5cb-772b-41b8-90f4-fc382cc8414b"),
                            Longname = "ROTHENSEER-VERBINDUNGSKANAL",
                            Shortname = "RVK"
                        },
                        new
                        {
                            Id = new Guid("28e2b1b8-e353-4174-99a5-816229c68bd1"),
                            Longname = "RUHR",
                            Shortname = "RUHR"
                        },
                        new
                        {
                            Id = new Guid("7314670d-020b-4c64-9870-84d5e2eb0ba4"),
                            Longname = "RUTHENSTROM",
                            Shortname = "Ruthenstrom"
                        },
                        new
                        {
                            Id = new Guid("c821c96d-eebc-4f9c-8bd8-2aa4a304fb23"),
                            Longname = "RÜDERSDORFER GEWÄSSER",
                            Shortname = "RÜG"
                        },
                        new
                        {
                            Id = new Guid("b61e88e8-9c3e-4ffa-8265-3c1053df076e"),
                            Longname = "SAALE",
                            Shortname = "SAALE"
                        },
                        new
                        {
                            Id = new Guid("2f810727-4e7b-40ac-8356-ad1477d49150"),
                            Longname = "SAAR",
                            Shortname = "SAAR"
                        },
                        new
                        {
                            Id = new Guid("262436f8-2a32-434b-9d19-90d1922daadc"),
                            Longname = "SCHWEDTER QUERFAHRT",
                            Shortname = "SQF"
                        },
                        new
                        {
                            Id = new Guid("714b47c3-c63b-426f-accc-bcb7ebdde0e3"),
                            Longname = "SCHWINGE",
                            Shortname = "Schwinge"
                        },
                        new
                        {
                            Id = new Guid("512a905c-fbd5-4e1f-ad61-caba44d8b0f9"),
                            Longname = "SPREE-ODER-WASSERSTRASSE",
                            Shortname = "SOW"
                        },
                        new
                        {
                            Id = new Guid("450a71cf-f2db-4932-96d9-33afcb7e1272"),
                            Longname = "STICHKANAL HILDESHEIM",
                            Shortname = "SKH"
                        },
                        new
                        {
                            Id = new Guid("c309f510-67ec-4d13-912d-f703231458cc"),
                            Longname = "STORKOWER GEWAESSER",
                            Shortname = "SKG"
                        },
                        new
                        {
                            Id = new Guid("87724dc3-a0e4-4fe3-af64-0c174951d58e"),
                            Longname = "STÖR",
                            Shortname = "STÖR"
                        },
                        new
                        {
                            Id = new Guid("10415159-e774-4431-8de1-5ce83324718f"),
                            Longname = "STÖR-WASSERSTRASSE",
                            Shortname = "STW"
                        },
                        new
                        {
                            Id = new Guid("def28f4a-9a97-4659-85f4-7a0f47ec3309"),
                            Longname = "TELTOWKANAL",
                            Shortname = "TeK"
                        },
                        new
                        {
                            Id = new Guid("177835d3-9d2a-42ef-88fd-a572ba3df9ca"),
                            Longname = "TEMPLINER GEWÄSSER",
                            Shortname = "TlG"
                        },
                        new
                        {
                            Id = new Guid("e47bbf30-f087-49dc-a85d-f097d829a39a"),
                            Longname = "TRAVE",
                            Shortname = "TRAVE"
                        },
                        new
                        {
                            Id = new Guid("3a151fd0-81a0-4b01-a439-d2aa553b0b38"),
                            Longname = "TREENE",
                            Shortname = "TREENE"
                        },
                        new
                        {
                            Id = new Guid("f68a87eb-4812-4075-a29c-82831687c30f"),
                            Longname = "UNTERE HAVEL-WASSERSTRASSE",
                            Shortname = "UHW"
                        },
                        new
                        {
                            Id = new Guid("7bd20795-fa24-4a48-ac2a-5c5c8510ea97"),
                            Longname = "VERBINDUNGSKANAL HOHENSAATEN",
                            Shortname = "VKH"
                        },
                        new
                        {
                            Id = new Guid("2b224064-51d8-451c-806a-836f4d7e707a"),
                            Longname = "VLATAVA",
                            Shortname = "MOLDAU"
                        },
                        new
                        {
                            Id = new Guid("63e486cf-7366-4c56-8d33-1f5f1874434b"),
                            Longname = "WARNOW",
                            Shortname = "WARNOW"
                        },
                        new
                        {
                            Id = new Guid("d30e6e98-5a25-40af-a625-be880ef69a9b"),
                            Longname = "WENTOW-GEWÄSSER",
                            Shortname = "WtG"
                        },
                        new
                        {
                            Id = new Guid("f1c53a5e-5205-4f4b-8463-c9c074919477"),
                            Longname = "WERBELLINER GEWÄSSER",
                            Shortname = "WbG"
                        },
                        new
                        {
                            Id = new Guid("808af9be-2074-40a7-96b1-17973bd59449"),
                            Longname = "WERRA",
                            Shortname = "WERRA"
                        },
                        new
                        {
                            Id = new Guid("1e045f5d-abab-4826-85ea-b9c3fcafc271"),
                            Longname = "WESEL-DATTELN-KANAL",
                            Shortname = "WDK"
                        },
                        new
                        {
                            Id = new Guid("f965ecf6-2057-479d-a571-3f4e30c1e493"),
                            Longname = "WESER",
                            Shortname = "WESER"
                        },
                        new
                        {
                            Id = new Guid("744e0bc7-0946-41ea-bc82-d0cea5cbf4c1"),
                            Longname = "WESTODER",
                            Shortname = "WOD"
                        },
                        new
                        {
                            Id = new Guid("c656debb-f595-41af-8234-48f3c4c19a51"),
                            Longname = "WISCHHAFENER SÜDERELBE",
                            Shortname = "Wischhafener Süderelbe"
                        },
                        new
                        {
                            Id = new Guid("4f626d5c-3e9d-4fe4-839a-df9eb0262ba0"),
                            Longname = "WÜMME",
                            Shortname = "WÜMME"
                        });
                });

            modelBuilder.Entity("com.b_velop.Slipways.GraphQL.Data.Models.Slipway", b =>
                {
                    b.HasOne("com.b_velop.Slipways.GraphQL.Data.Models.Water", "Water")
                        .WithMany("Slipways")
                        .HasForeignKey("WaterFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("com.b_velop.Slipways.GraphQL.Data.Models.Station", b =>
                {
                    b.HasOne("com.b_velop.Slipways.GraphQL.Data.Models.Water", "Water")
                        .WithMany("Stations")
                        .HasForeignKey("WaterFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
